<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-KKCKK7S" failures="1" tests="7" name="Default test" time="6.575" errors="0" timestamp="2021-06-03T12:48:47 BST">
  <testcase classname="Manager.NewCustomer" name="openbrowser" time="4.718"/>
  <testcase classname="Manager.NewCustomer" name="NC29" time="0.744">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Email-ID is not valid] but found [Email-ID must not be blank]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Email-ID is not valid] but found [Email-ID must not be blank]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at Manager.NewCustomer.NC29(NewCustomer.java:344)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- NC29 -->
  <testcase classname="Manager.NewCustomer" name="NC27" time="0.44"/>
  <testcase classname="Manager.NewCustomer" name="NC1" time="0.362"/>
  <testcase classname="Manager.NewCustomer" name="closebrowser" time="0.17"/>
  <testcase classname="Manager.annotationexample" name="method1" time="0.013"/>
  <testcase classname="Manager.annotationexample1" name="method2" time="0.006"/>
  <testcase classname="Manager.NewCustomer" name="NC2" time="0.0">
    <ignored/>
  </testcase> <!-- NC2 -->
</testsuite> <!-- Default test -->
